# Generated by Django 3.1.7 on 2021-03-28 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20210327_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='viagem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hackathon.viagem', verbose_name='Viagem'),
        ),
    ]
