# Generated by Django 3.1.7 on 2021-03-28 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_extras_viagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='ativadade',
        ),
        migrations.AddField(
            model_name='extras',
            name='ativadade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hackathon.atividade', verbose_name='Atividade'),
        ),
        migrations.RemoveField(
            model_name='extras',
            name='hospedagem',
        ),
        migrations.AddField(
            model_name='extras',
            name='hospedagem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hackathon.hospedagem', verbose_name='Hospedagem'),
        ),
        migrations.RemoveField(
            model_name='extras',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='extras',
            name='restaurante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hackathon.restaurante', verbose_name='Restaurante'),
        ),
    ]
