# Generated by Django 3.1.7 on 2021-03-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_auto_20210327_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Preço'),
        ),
    ]
