# Generated by Django 3.1.7 on 2021-03-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_lugar_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Preço'),
        ),
    ]
